services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9222:9000"
      - "9223:9001"
    volumes:
      - minio-volume:/data
    command: minio server /data --address 0.0.0.0:9000 --console-address 0.0.0.0:9001

volumes:
  minio-volume: